<a href="https://colab.research.google.com/github/ugnature/Tensor_flow/blob/main/Tensor_Flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow and Variables

## Initialization and Casting

### Tensors are Multi Dimentional Arrays

* An array is an *ordered arrangement of numbers*

In [18]:
import tensorflow as tf

In [19]:
# Create our first zero dimenstion tensor which contain only one element in a tensor
tensor_zero_d = tf.constant(2)
print(tensor_zero_d)

tf.Tensor(2, shape=(), dtype=int32)


In [20]:
# Create our first one dimention tensor
tensor_one_d = tf.constant([2, 0, -3, 9, 10, 123], dtype= tf.float32)
print(tensor_one_d)
# lets try to turn this into boolean
tensor_bool_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_bool_one_d) # wherever the value will be zero, it will be converted as false

tf.Tensor([  2.   0.  -3.   9.  10. 123.], shape=(6,), dtype=float32)
tf.Tensor([ True False  True  True  True  True], shape=(6,), dtype=bool)


In [216]:
# Create our first two dimension tensor
tensor_two_d = tf.constant([
                            [1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]], dtype=tf.float32)
print(tensor_two_d)

tf.Tensor(
[[ 1.  2.  0.]
 [ 3.  5. -1.]
 [ 1.  5.  6.]
 [ 2.  3.  8.]], shape=(4, 3), dtype=float32)


In [22]:
# Create our first 3d tensor
tensor_three_d = tf.constant(
                            [[[1, 2, 0],
                             [3, 5, -1]],

                            [[10, 2, 0],
                             [1, 0, 2]],

                            [[5, 8, 0],
                             [2, 7, 0]],

                            [[2, 1, 9],
                             [4, -3, 32]]]
)
print(tensor_three_d)
print("------------------------")
print(f"tensor shape: {tensor_three_d.shape}")
print(f"tensor dimension: {tensor_three_d.ndim}d")

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
------------------------
tensor shape: (4, 2, 3)
tensor dimension: 3d


In [23]:
# Create our first four dimension tensor
tensor_four_d = tf.constant(
                            [[[[1, 2, 0],
                             [3, 5, -1]],

                             [[10, 2, 0],
                             [1, 0, 2]],

                             [[5, 8, 0],
                             [2, 7, 0]],

                             [[2, 1, 9],
                             [4, -3, 32]]],
                             
                                           [[[4, 5, 4],
                                             [3, 1, 1]],
                             
                                             [[0, 2, 5],
                                              [0, 4, 3]],
                             
                                             [[3, 2, 4],
                                              [5, 8 ,3]],
                             
                                             [[8, 2, 5],
                                              [2, 3, 3]]],
                                                          [[[0, 2, 4],
                                                            [5, 3, 1]],
                                                           
                                                           [[0, 2, 0],
                                                            [-1, 10, 0]],
                                                           
                                                           [[0, 5, 1],
                                                            [1, 7, 0]],
                                                           
                                                           [[3, 8, 7],
                                                            [2, 3, 2]]]])
print(tensor_four_d)
print("------------------------")
print(f"tensor shape: {tensor_four_d.shape}")
print(f"tensor dimension: {tensor_four_d.ndim}d")

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]


 [[[ 0  2  4]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]], shape=(3, 4, 2, 3), dtype=int32)
------------------------
tensor shape: (3, 4, 2, 3)
tensor dimension: 4d


In [24]:
# lets create our first boolean tensor
tensor_bool = tf.constant([[True, False, True],
                          [True, False, False]])
print(tensor_bool)
# lets try to turn this tensor into int
tensor_int = tf.cast(tensor_bool, dtype=tf.int32)
print(tensor_int) # true will be converted as 1 and false will be as 0

tf.Tensor(
[[ True False  True]
 [ True False False]], shape=(2, 3), dtype=bool)
tf.Tensor(
[[1 0 1]
 [1 0 0]], shape=(2, 3), dtype=int32)


In [25]:
# Lets create our first tensor of string
tensor_string = tf.constant([["Vinay", "Abhay", "Shantanu"],
                            ["Anjum", "Deevangi", "Tharak"]])
print(tensor_string)

tf.Tensor(
[[b'Vinay' b'Abhay' b'Shantanu']
 [b'Anjum' b'Deevangi' b'Tharak']], shape=(2, 3), dtype=string)


### Let's learn how to convert NumPy array into Tensor

In [26]:
# Lets convert NumPy array to Tensor
import numpy as np
np_array = np.array([1, 3, 4])
print(np_array)

[1 3 4]


In [27]:
converted_tensor = tf.convert_to_tensor(np_array, dtype= tf.float32)
print(converted_tensor)

tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32)


### Identical Tensors
**Identical Tensors**
`tf.eye`

In [28]:
# create tensor automatically but they are going to identical
# using batchshape in eye method we create identity matrix
identity_matrix = tf.eye(
                          num_rows= 5, 
                          num_columns= None, 
                          batch_shape=[2, 3], 
                          dtype= tf.int64,
                          name=None)
print(identity_matrix)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]], shape=(2, 3, 5, 5), dtype=int64)


### Tensor filled with scalar value or in other word zero dimensions values
**Scalar Value tensor** of any dimension:
`tf.fill`

In [29]:
# scalar meaning zero dimension tensors
tensor_scaler_fill = tf.fill(dims=[4, 3, 6], value=4)
print(tensor_scaler_fill)

tf.Tensor(
[[[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]], shape=(4, 3, 6), dtype=int32)


### Creation of Tensor with all element are set to one
**Tensor One** `tf.ones`

In [30]:
tensor_one = tf.ones([2, 5, 5], dtype=tf.float16)
print(tensor_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 5, 5), dtype=float16)


### Tensor Ones_like
It's just imitate the shape of your tensor but the value will be given as one
**Tensor ones_like**: `tf.ones_like`

In [31]:
tensor = tf.constant([[1, 3, 5],
                      [2, 5, 6],
                      [2, 55, 6]], dtype=tf.float32)
# lets imitate the above tensor
tensor_ones_like = tf.ones_like(tensor)
print(tensor_ones_like)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


### Creation of Tensor with all element are set to zero
**Tensor Zero** `tf.zeros`

In [32]:
# Create a tensor with zero staler
tensor_zero = tf.zeros([2, 5, 6], dtype= tf.int32)
print(tensor_zero)

tf.Tensor(
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]], shape=(2, 5, 6), dtype=int32)


### Let's findout tha shape of the tensor

In [33]:
# lets find out the shape of the tensor
tensor_shape = tf.shape(tensor_zero)
print(tensor_shape)

tf.Tensor([2 5 6], shape=(3,), dtype=int32)


In [34]:
# lets find out the rank also
# rank stand for dimension stage
tensor_rank = tf.rank(tensor_zero)
print(tensor_rank)

tf.Tensor(3, shape=(), dtype=int32)


In [35]:
# lets find out the size also of our four_d tensor (3, 4, 2, 3)
# this will return zero d tensors in total
tensor_size = tf.size(tensor_four_d, out_type=tf.float32)
print(tensor_size)

tf.Tensor(72.0, shape=(), dtype=float32)


### Lets create a random.normal Tensor
Using: `tf.random.normal`

In [36]:
# create first random tensor
# tf.random.set_seed(108);
my_random_tensor= tf.random.normal(
    shape=[2, 4, 3],
    mean=0.2,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(my_random_tensor)

tf.Tensor(
[[[ 1.5372868   1.8413193  -1.25552   ]
  [-0.18345682  1.3726352   1.0807921 ]
  [ 0.4802217  -0.00744937  2.1154366 ]
  [ 1.2224411   0.20632002  1.8528371 ]]

 [[ 1.1050026  -0.6330713   0.39583114]
  [-2.861673    0.40034133 -0.72476655]
  [ 0.18139207 -0.16243558 -0.42183393]
  [-0.53782964 -0.2838322   0.6884018 ]]], shape=(2, 4, 3), dtype=float32)


### Lets create a random.uniform Tensor
Using: `tf.random.uniform`

In [37]:
# it is totally abstract
tf.random.set_seed(108)
tensor_uniform = tf.random.uniform(
    shape=[2, 4, 2, 3],
    minval=1,
    maxval=108,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None)
print(tensor_uniform)

tf.Tensor(
[[[[ 80  79   3]
   [  6  29  20]]

  [[106  48  53]
   [ 88  63  33]]

  [[ 37  13  10]
   [ 51   3  61]]

  [[  3  57  63]
   [ 43  42  52]]]


 [[[ 13  19  21]
   [ 49  81 103]]

  [[ 43  87   8]
   [  9  18  94]]

  [[ 69   4  99]
   [ 46  93 102]]

  [[101  17  24]
   [ 27  77  87]]]], shape=(2, 4, 2, 3), dtype=int32)


# Indexing

`**indexing** (minindex:maxindex:step)`

In [38]:
import tensorflow as tf
tensor_indexing = tf.constant([2, 4, 34, 3, 7, 8])
print(tensor_indexing)
# lets get the first four index
print(tensor_indexing[2:-1])
# indexing (minindex:maxindex:step)
print(tensor_indexing[1:7:1])

tf.Tensor([ 2  4 34  3  7  8], shape=(6,), dtype=int32)
tf.Tensor([34  3  7], shape=(3,), dtype=int32)
tf.Tensor([ 4 34  3  7  8], shape=(5,), dtype=int32)


In [87]:
# Now do indexing in two_dimension tensor
print(tensor_two_d)
# Lets do indexing
print("\nindexing result\n")
print(tensor_two_d[1:])
print("--------------------")
print(tensor_two_d[:,2:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int64)

indexing result

tf.Tensor(
[[ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(3, 3), dtype=int64)
--------------------
tf.Tensor(
[[ 0]
 [-1]
 [ 6]
 [ 8]], shape=(4, 1), dtype=int64)


In [138]:
# Lets work on 3d tensor
print(tensor_three_d)
print("\nIndex Result\n")
print(tensor_three_d[..., 1:3, 1:])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)

Index Result

tf.Tensor(
[[[ 5 -1]]

 [[ 0  2]]

 [[ 7  0]]

 [[-3 32]]], shape=(4, 1, 2), dtype=int32)


# Math Operators

#### `tf.math.abs`

* what abs do -> it just turn the -ve(negative value) into positive(+ve), if the input value is already positive in the tensor than it keeps that value, don't tuch it


In [142]:
x_abs = tf.constant([1, -2, -178])
tf.abs(x_abs)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,   2, 178], dtype=int32)>

In [149]:
# complex number
x_complex_abs = tf.constant([[-244 + 3.5j], [-34435 + 4.5j]])
tf.abs(x_complex_abs)


<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[  244.02510117],
       [34435.00029403]])>

In [167]:
tf.sqrt( (244)**2 + 3.5**2)

<tf.Tensor: shape=(), dtype=float32, numpy=244.0251>

#### `tf.math.add`

In [177]:
x_1 = tf.constant([2, 4, 55, 76, 3], dtype= tf.float32)
x_2 = tf.constant([22, 4, 355, 276, 2323], dtype= tf.float32)
x_3 = 3
addition= tf.add(x_1, x_3, x_2)
print(addition)

tf.Tensor([ 5.  7. 58. 79.  6.], shape=(5,), dtype=float32)


#### `tf.math.multiply`

In [210]:
x1= tf.constant([2, 2, 5, 6, 76, 74], dtype= tf.float32)
x2= tf.constant([[2], [3], [9]], dtype= tf.float32)
print(x1.shape)
print(x2.shape)
tf.multiply(x1, x2 )

(6,)
(3, 1)


<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[  4.,   4.,  10.,  12., 152., 148.],
       [  6.,   6.,  15.,  18., 228., 222.],
       [ 18.,  18.,  45.,  54., 684., 666.]], dtype=float32)>

#### `tf.math.subtract`

In [181]:
tf.subtract(x_1, x_2)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([  -20.,     0.,  -300.,  -200., -2320.], dtype=float32)>

#### `tf.math.divide`

In [182]:
tf.divide(x_1, x_2)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.09090909, 1.        , 0.15492958, 0.2753623 , 0.00129143],
      dtype=float32)>

In [219]:
xz = tf.constant([1, -3, 5, 7, 8], dtype=tf.float32)
yz = tf.constant([0, -4, 5, 0, 0], dtype=tf.float32)
# you will see inf(infinite) written in the result because we are trying to devide something by 0

print(tf.math.divide(xz, yz))
# to handle this situation we have something called tf.math.divide_no_nan
print(tf.math.divide_no_nan(xz, yz))

tf.Tensor([ inf 0.75 1.    inf  inf], shape=(5,), dtype=float32)
tf.Tensor([0.   0.75 1.   0.   0.  ], shape=(5,), dtype=float32)


In [191]:
x = tf.constant([1, 4, 5, 7, 8], dtype=tf.float32)
y = tf.constant(0, dtype=tf.float32)
# you will see inf(infinite) written in the result because we are trying to devide something by 0

print(tf.math.divide(x, y))
# to handle this situation we have something called tf.math.divide_no_nan
print(tf.math.divide_no_nan(x, y))

tf.Tensor([inf inf inf inf inf], shape=(5,), dtype=float32)
tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)


#### `tf.math.maximum`

In [220]:
# to get or findout maximum values from your tensors values, use this:
tf.math.maximum(xz, yz)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1., -3.,  5.,  7.,  8.], dtype=float32)>

#### `tf.math.argmax`

* argmax finds the higest value position on perticular index

In [236]:
x_argmax = tf.constant([1112, 120, 30, 3, 6])
print(x_argmax.shape)
tf.math.argmax(x_argmax)


(5,)


<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [245]:
x_argmax2 = tf.constant([[2, 20, 30, 3, 6], 
                        [3, 11, 16, 13, 80],
                        [14, 45, 23, 5, 27]])
print(x_argmax2.shape)
tf.math.argmin(x_argmax2, 1)


(3, 5)


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 3])>

#### `tf.math.pow`

it is like 2 ki power 2 = 4

In [254]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[1, 4], [1, 0]])
tf.pow(x, y)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 16],
       [ 3,  1]], dtype=int32)>

#### `tf.math.reduce_sum`
* This just reduce the value inside the tensor meaning summing of the values
* You can choose the option of axis meaning want to sum vertical values or horizonal or say all than u have to keep is None

In [269]:
print(tensor_two_d)
print("-------------to sum all---------------")
print(tf.math.reduce_sum(
                   tensor_two_d, 
                   axis=None, 
                   keepdims=False, 
                   name=None))
print("------------\nTo reduce the tensor to the higest value----------------")
print(tf.math.reduce_max(
                   tensor_two_d, 
                   axis=None, 
                   keepdims=False, 
                   name=None))
print("--------------\nTo reduce the tensor to the lowest value--------------")
print(tf.math.reduce_min(
                   tensor_two_d, 
                   axis=None, 
                   keepdims=False, 
                   name=None))


tf.Tensor(
[[ 1.  2.  0.]
 [ 3.  5. -1.]
 [ 1.  5.  6.]
 [ 2.  3.  8.]], shape=(4, 3), dtype=float32)
-------------to sum all---------------
tf.Tensor(35.0, shape=(), dtype=float32)
------------
To reduce the tensor to the higest value----------------
tf.Tensor(8.0, shape=(), dtype=float32)
--------------
To reduce the tensor to the lowest value--------------
tf.Tensor(-1.0, shape=(), dtype=float32)
