<a href="https://colab.research.google.com/github/ugnature/Tensor_flow/blob/main/Tensor_Flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow and Variables

## Initialization and Casting

### Tensors are Multi Dimentional Arrays

* An array is an *ordered arrangement of numbers*

In [11]:
import tensorflow as tf

In [12]:
# Create our first zero dimenstion tensor which contain only one element in a tensor
tensor_zero_d = tf.constant(2)
print(tensor_zero_d)

tf.Tensor(2, shape=(), dtype=int32)


In [39]:
# Create our first one dimention tensor
tensor_one_d = tf.constant([2, 0, -3, 9, 10, 123], dtype= tf.float32)
print(tensor_one_d)
# lets try to turn this into boolean
tensor_bool_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_bool_one_d) # wherever the value will be zero, it will be converted as false

tf.Tensor([  2.   0.  -3.   9.  10. 123.], shape=(6,), dtype=float32)
tf.Tensor([ True False  True  True  True  True], shape=(6,), dtype=bool)


In [32]:
# Create our first two dimension tensor
tensor_two_d = tf.constant([
                            [1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]], dtype=tf.int64)
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int64)


In [26]:
# Create our first 3d tensor
tensor_three_d = tf.constant(
                            [[[1, 2, 0],
                             [3, 5, -1]],

                            [[10, 2, 0],
                             [1, 0, 2]],

                            [[5, 8, 0],
                             [2, 7, 0]],

                            [[2, 1, 9],
                             [4, -3, 32]]]
)
print(tensor_three_d)
print("------------------------")
print(f"tensor shape: {tensor_three_d.shape}")
print(f"tensor dimension: {tensor_three_d.ndim}d")

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
------------------------
tensor shape: (4, 2, 3)
tensor dimension: 3d


In [28]:
# Create our first four dimension tensor
tensor_four_d = tf.constant(
                            [[[[1, 2, 0],
                             [3, 5, -1]],

                             [[10, 2, 0],
                             [1, 0, 2]],

                             [[5, 8, 0],
                             [2, 7, 0]],

                             [[2, 1, 9],
                             [4, -3, 32]]],
                             
                                           [[[4, 5, 4],
                                             [3, 1, 1]],
                             
                                             [[0, 2, 5],
                                              [0, 4, 3]],
                             
                                             [[3, 2, 4],
                                              [5, 8 ,3]],
                             
                                             [[8, 2, 5],
                                              [2, 3, 3]]],
                                                          [[[0, 2, 4],
                                                            [5, 3, 1]],
                                                           
                                                           [[0, 2, 0],
                                                            [-1, 10, 0]],
                                                           
                                                           [[0, 5, 1],
                                                            [1, 7, 0]],
                                                           
                                                           [[3, 8, 7],
                                                            [2, 3, 2]]]])
print(tensor_four_d)
print("------------------------")
print(f"tensor shape: {tensor_four_d.shape}")
print(f"tensor dimension: {tensor_four_d.ndim}d")

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]


 [[[ 0  2  4]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]], shape=(3, 4, 2, 3), dtype=int32)
------------------------
tensor shape: (3, 4, 2, 3)
tensor dimension: 4d


In [43]:
# lets create our first boolean tensor
tensor_bool = tf.constant([[True, False, True],
                          [True, False, False]])
print(tensor_bool)
# lets try to turn this tensor into int
tensor_int = tf.cast(tensor_bool, dtype=tf.int32)
print(tensor_int) # true will be converted as 1 and false will be as 0

tf.Tensor(
[[ True False  True]
 [ True False False]], shape=(2, 3), dtype=bool)
tf.Tensor(
[[1 0 1]
 [1 0 0]], shape=(2, 3), dtype=int32)


In [44]:
# Lets create our first tensor of string
tensor_string = tf.constant([["Vinay", "Abhay", "Shantanu"],
                            ["Anjum", "Deevangi", "Tharak"]])
print(tensor_string)

tf.Tensor(
[[b'Vinay' b'Abhay' b'Shantanu']
 [b'Anjum' b'Deevangi' b'Tharak']], shape=(2, 3), dtype=string)


### Let's learn how to convert NumPy array into Tensor

In [46]:
# Lets convert NumPy array to Tensor
import numpy as np
np_array = np.array([1, 3, 4])
print(np_array)

[1 3 4]


In [49]:
converted_tensor = tf.convert_to_tensor(np_array, dtype= tf.float32)
print(converted_tensor)

tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32)


### Identical Tensors
**Identical Tensors**
`tf.eye`

In [79]:
# create tensor automatically but they are going to identical
# using batchshape in eye method we create identity matrix
identity_matrix = tf.eye(
                          num_rows= 5, 
                          num_columns= None, 
                          batch_shape=[2, 3], 
                          dtype= tf.int64,
                          name=None)
print(identity_matrix)

tf.Tensor(
[[[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]


 [[[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]

  [[1 0 0 0 0]
   [0 1 0 0 0]
   [0 0 1 0 0]
   [0 0 0 1 0]
   [0 0 0 0 1]]]], shape=(2, 3, 5, 5), dtype=int64)


### Tensor filled with scalar value or in other word zero dimensions values
**Scalar Value tensor** of any dimension:
`tf.fill`

In [86]:
# scalar meaning zero dimension tensors
tensor_scaler_fill = tf.fill(dims=[4, 3, 6], value=4)
print(tensor_scaler_fill)

tf.Tensor(
[[[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]
  [4 4 4 4 4 4]]], shape=(4, 3, 6), dtype=int32)


### Creation of Tensor with all element are set to one
**Tensor One** `tf.ones`

In [89]:
tensor_one = tf.ones([2, 5, 5], dtype=tf.float16)
print(tensor_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 5, 5), dtype=float16)


### Tensor Ones_like
It's just imitate the shape of your tensor but the value will be given as one
**Tensor ones_like**: `tf.ones_like`

In [94]:
tensor = tf.constant([[1, 3, 5],
                      [2, 5, 6],
                      [2, 55, 6]], dtype=tf.float32)
# lets imitate the above tensor
tensor_ones_like = tf.ones_like(tensor)
print(tensor_ones_like)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


### Creation of Tensor with all element are set to zero
**Tensor Zero** `tf.zeros`

In [96]:
# Create a tensor with zero staler
tensor_zero = tf.zeros([2, 5, 6], dtype= tf.int32)
print(tensor_zero)

tf.Tensor(
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]], shape=(2, 5, 6), dtype=int32)


### Let's findout tha shape of the tensor

In [98]:
# lets find out the shape of the tensor
tensor_shape = tf.shape(tensor_zero)
print(tensor_shape)

tf.Tensor([2 5 6], shape=(3,), dtype=int32)


In [103]:
# lets find out the rank also
# rank stand for dimension stage
tensor_rank = tf.rank(tensor_zero)
print(tensor_rank)

tf.Tensor(3, shape=(), dtype=int32)


In [108]:
# lets find out the size also of our four_d tensor (3, 4, 2, 3)
# this will return zero d tensors in total
tensor_size = tf.size(tensor_four_d, out_type=tf.float32)
print(tensor_size)

tf.Tensor(72.0, shape=(), dtype=float32)


### Lets create a random.normal Tensor
Using: `tf.random.normal`

In [171]:
# create first random tensor
# tf.random.set_seed(108);
my_random_tensor= tf.random.normal(
    shape=[2, 4, 3],
    mean=0.2,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(my_random_tensor)

tf.Tensor(
[[[ 0.18908949  0.6130406  -0.9811397 ]
  [-0.5617257  -0.282296   -0.65634495]
  [ 0.7194519   0.5531581   0.6013858 ]
  [-1.758456   -0.5455282  -0.62977475]]

 [[-0.3492217  -0.25235772 -0.110038  ]
  [ 1.0042791  -0.7709881   0.680386  ]
  [-0.25373942  0.13273308 -0.4869988 ]
  [ 0.44678408  0.33951098  0.6623259 ]]], shape=(2, 4, 3), dtype=float32)


### Lets create a random.uniform Tensor
Using: `tf.random.uniform`

In [203]:
# this tensor is without mean and deviation
# it is totally abstract
tf.random.set_seed(108)
tensor_uniform = tf.random.uniform(
    shape=[2, 4, 2, 3],
    minval=1,
    maxval=108,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None)
print(tensor_uniform)

tf.Tensor(
[[[[ 80  79   3]
   [  6  29  20]]

  [[106  48  53]
   [ 88  63  33]]

  [[ 37  13  10]
   [ 51   3  61]]

  [[  3  57  63]
   [ 43  42  52]]]


 [[[ 13  19  21]
   [ 49  81 103]]

  [[ 43  87   8]
   [  9  18  94]]

  [[ 69   4  99]
   [ 46  93 102]]

  [[101  17  24]
   [ 27  77  87]]]], shape=(2, 4, 2, 3), dtype=int32)


## Indexing