<a href="https://colab.research.google.com/github/ugnature/Tensor_flow/blob/main/Tensor_Flow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

### Tensors are Multi Dimentional Arrays

* An array is an *ordered arrangement of numbers*

In [11]:
import tensorflow as tf

In [12]:
# Create our first zero dimenstion tensor which contain only one element in a tensor
tensor_zero_d = tf.constant(2)
print(tensor_zero_d)

tf.Tensor(2, shape=(), dtype=int32)


In [16]:
# Create our first one dimention tensor
tensor_one_d = tf.constant([2, 0, -3, 9, 10, 123])
print(tensor_one_d)

tf.Tensor([  2   0  -3   9  10 123], shape=(6,), dtype=int32)


In [19]:
# Create our first two dimension tensor
tensor_two_d = tf.constant([
                            [1, 2, 0],
                            [3, 5, -1],
                            [1, 5, 6],
                            [2, 3, 8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [26]:
# Create our first 3d tensor
tensor_three_d = tf.constant(
                            [[[1, 2, 0],
                             [3, 5, -1]],

                            [[10, 2, 0],
                             [1, 0, 2]],

                            [[5, 8, 0],
                             [2, 7, 0]],

                            [[2, 1, 9],
                             [4, -3, 32]]]
)
print(tensor_three_d)
print("------------------------")
print(f"tensor shape: {tensor_three_d.shape}")
print(f"tensor dimension: {tensor_three_d.ndim}d")

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
------------------------
tensor shape: (4, 2, 3)
tensor dimension: 3d


In [28]:
# Create our first four dimension tensor
tensor_four_d = tf.constant(
                            [[[[1, 2, 0],
                             [3, 5, -1]],

                             [[10, 2, 0],
                             [1, 0, 2]],

                             [[5, 8, 0],
                             [2, 7, 0]],

                             [[2, 1, 9],
                             [4, -3, 32]]],
                             
                                           [[[4, 5, 4],
                                             [3, 1, 1]],
                             
                                             [[0, 2, 5],
                                              [0, 4, 3]],
                             
                                             [[3, 2, 4],
                                              [5, 8 ,3]],
                             
                                             [[8, 2, 5],
                                              [2, 3, 3]]],
                                                          [[[0, 2, 4],
                                                            [5, 3, 1]],
                                                           
                                                           [[0, 2, 0],
                                                            [-1, 10, 0]],
                                                           
                                                           [[0, 5, 1],
                                                            [1, 7, 0]],
                                                           
                                                           [[3, 8, 7],
                                                            [2, 3, 2]]]])
print(tensor_four_d)
print("------------------------")
print(f"tensor shape: {tensor_four_d.shape}")
print(f"tensor dimension: {tensor_four_d.ndim}d")

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]


 [[[ 0  2  4]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]], shape=(3, 4, 2, 3), dtype=int32)
------------------------
tensor shape: (3, 4, 2, 3)
tensor dimension: 4d
